# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hw1.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Q1controller import * 
from Q2controller import *
from Q3controller import *

class Ui_MainWindow(object):
    def __init__(self) -> None:
        super().__init__()
        self.verbose = False

    def verboseButtonClicked(self):
        self.verbose = not self.verbose
        _translate = QtCore.QCoreApplication.translate
        self.verboseButton.setText(_translate("MainWindow", "verbose: " + str(self.verbose)))
        print(self.verbose)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1069, 650)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 251, 611))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        # 1-1 Load Image
        self.loadImageButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.loadImageButton.setObjectName("loadImageButton")
        self.verticalLayout.addWidget(self.loadImageButton)
        self.loadImageButton.clicked.connect(loadImageButtonClicked)
        # 1-2 Color Separation
        self.colorSeparateButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.colorSeparateButton.setObjectName("colorSeparateButton")
        self.verticalLayout.addWidget(self.colorSeparateButton)
        self.colorSeparateButton.clicked.connect(colorSeparateButtonClicked)
        # 1-3 Color Transformation
        self.colorTransformateButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.colorTransformateButton.setObjectName("colorTransformateButton")
        self.verticalLayout.addWidget(self.colorTransformateButton)
        self.colorTransformateButton.clicked.connect(colorTransformateButtonClicked)
        # 1-4 Blending
        self.blendingButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.blendingButton.setObjectName("blendingButton")
        self.verticalLayout.addWidget(self.blendingButton)
        self.blendingButton.clicked.connect(blendingButtonClicked)

        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(270, 10, 251, 611))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        # 2-1 Gaussian Blur
        self.gaussianBlurButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.gaussianBlurButton.setObjectName("gaussianBlurButton")
        self.verticalLayout_2.addWidget(self.gaussianBlurButton)
        self.gaussianBlurButton.clicked.connect(gaussianBlurButtonClicked)
        # 2-2 Bilateral Filter
        self.bilateralFilterButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.bilateralFilterButton.setObjectName("bilateralFilterButton")
        self.verticalLayout_2.addWidget(self.bilateralFilterButton)
        self.bilateralFilterButton.clicked.connect(bilateralFilterButtonClicked)
        # 2-3 Median Filter
        self.medianFilterButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.medianFilterButton.setObjectName("medianFilterButton")
        self.verticalLayout_2.addWidget(self.medianFilterButton)
        self.medianFilterButton.clicked.connect(medianFilterButtonClicked)

        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(530, 10, 251, 611))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        # 3-1 Gaussian Blur Edge 
        self.verboseButton = QtWidgets.QPushButton(self.centralwidget)
        self.verboseButton.setGeometry(QtCore.QRect(565, 575, 200, 25))
        self.verboseButton.setObjectName("verboseButton")
        self.verboseButton.clicked.connect(self.verboseButtonClicked)

        self.gaussianBlurEdgeButton = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.gaussianBlurEdgeButton.setObjectName("gaussianBlurEdgeButton")
        self.verticalLayout_3.addWidget(self.gaussianBlurEdgeButton)
        self.gaussianBlurEdgeButton.clicked.connect(lambda:gaussianBlurEdgeButtonClicked(self.verbose))
        # 3-2 Sobel X
        self.SobelXButton = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.SobelXButton.setObjectName("SobelXButton")
        self.verticalLayout_3.addWidget(self.SobelXButton)
        self.SobelXButton.clicked.connect(lambda:SobelXButtonClicked(self.verbose))
        # 3-3 Sobel Y
        self.SobelYButton = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.SobelYButton.setObjectName("SobelYButton")
        self.verticalLayout_3.addWidget(self.SobelYButton)
        self.SobelYButton.clicked.connect(lambda:SobelYButtonClicked(self.verbose))
        # 3-4 Magnitude 
        self.MagnitudeButton = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.MagnitudeButton.setObjectName("MagnitudeButton")
        self.verticalLayout_3.addWidget(self.MagnitudeButton)
        self.MagnitudeButton.clicked.connect(lambda:MagnitudeButtonClicked(self.verbose))

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.loadImageButton.setText(_translate("MainWindow", "1. Load Image File"))
        self.colorSeparateButton.setText(_translate("MainWindow", "2. Color Separation"))
        self.colorTransformateButton.setText(_translate("MainWindow", "3. Color Transformation"))
        self.blendingButton.setText(_translate("MainWindow", "4. Blending"))

        self.gaussianBlurButton.setText(_translate("MainWindow", "1. Gaussian Blur"))
        self.bilateralFilterButton.setText(_translate("MainWindow", "2. Bilateral Filter"))
        self.medianFilterButton.setText(_translate("MainWindow", "3. Median Filter"))
        self.verboseButton.setText(_translate("MainWindow", "verbose: " + str(self.verbose)))
        self.gaussianBlurEdgeButton.setText(_translate("MainWindow", "1. Self Defined Gaussian Blur"))
        self.SobelXButton.setText(_translate("MainWindow", "2. Sobel X"))
        self.SobelYButton.setText(_translate("MainWindow", "3. Sobel Y"))
        self.MagnitudeButton.setText(_translate("MainWindow", "4. Magnitude"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
